package wow.artificerpi.tools;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.Iterator;

import org.apache.commons.io.FileUtils;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private Downloader dl;

	public App() {
		this.dl = new Downloader();
	}

	public void run() throws Exception {
		this.dl.downloadSelenium();
		this.dl.downloadChromeDriver();
	}

	public static void main(String[] args) {
		System.out.println("Running");
		try {
			new App().run();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			System.out.println("Done!");
		}
	}

}
